"""updated user table

Revision ID: 949d90ae33f2
Revises: 
Create Date: 2023-11-01 16:17:20.344400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949d90ae33f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('lecturer', sa.String(length=1000), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=550),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('stop_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('type')

    with op.batch_alter_table('upcoming_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('lecturer', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=120), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=550),
               existing_nullable=False)
        batch_op.drop_column('venue')
        batch_op.drop_column('type')

    with op.batch_alter_table('upcoming_presentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('lecturer', sa.String(length=250), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=550),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('stop_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('type')

    with op.batch_alter_table('upcoming_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('lecturer', sa.String(length=1000), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=550),
               existing_nullable=False)
        batch_op.alter_column('venue',
               existing_type=sa.DATE(),
               type_=sa.String(length=550),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('stop_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code_expiration')
        batch_op.drop_column('verification_code')

    with op.batch_alter_table('upcoming_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('stop_time',
               existing_type=sa.String(length=120),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=120),
               type_=sa.TIME(),
               nullable=False)
        batch_op.alter_column('venue',
               existing_type=sa.String(length=550),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=550),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('lecturer')
        batch_op.drop_column('course_title')

    with op.batch_alter_table('upcoming_presentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('stop_time',
               existing_type=sa.String(length=120),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=120),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(length=550),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('lecturer')
        batch_op.drop_column('course_title')

    with op.batch_alter_table('upcoming_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('venue', sa.VARCHAR(length=550), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.String(length=550),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('time')
        batch_op.drop_column('lecturer')
        batch_op.drop_column('course_title')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('stop_time',
               existing_type=sa.String(length=120),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=120),
               type_=sa.TIME(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=550),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('lecturer')
        batch_op.drop_column('course_title')

    # ### end Alembic commands ###
