"""empty message

Revision ID: b4686d9efcff
Revises: a29b72c57c2a
Create Date: 2023-11-03 16:50:57.231075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4686d9efcff'
down_revision = 'a29b72c57c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('faculty',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('institution',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('matno',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
        batch_op.alter_column('matno',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('institution',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('faculty',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
